### ISSUE TITLE
[NEED SUPPORT] bbexample-lt_1.0.bb:do_compile FAILED

### ISSUE THREAD

**Issue by FavoRiteKK** [DynamicDevices/bbexample#2]
I've tried to build bbexample-lt, but do_compile task failed.
My environment:

- Yocto 2.5.1
- poky master branch
- Ubuntu 16.04 LTS as host

Could someone help?
The error logs:

> Loading cache: 100% |############################################| Time: 0:00:01
> Loaded 1263 entries from dependency cache.
> NOTE: Resolving any missing task queue dependencies
> 
> Build Configuration:
> BB_VERSION           = "1.39.1"
> BUILD_SYS            = "x86_64-linux"
> NATIVELSBSTRING      = "universal"
> TARGET_SYS           = "i586-poky-linux"
> MACHINE              = "qemux86"
> DISTRO               = "poky"
> DISTRO_VERSION       = "2.5+snapshot-20181010"
> TUNE_FEATURES        = "m32 i586"
> TARGET_FPU           = ""
> meta                 
> meta-poky            
> meta-yocto-bsp       = "master:90028f3771a594d0cfb9560f463f2d15f052599e"
> meta-example         = "master:5ee4f20b041bc886b1d2d913ac11814057317634"
> 
> Initialising tasks: 100% |#######################################| Time: 0:00:01
> Sstate summary: Wanted 6 Found 0 Missed 6 Current 72 (0% match, 92% complete)
> NOTE: Executing SetScene Tasks
> NOTE: Executing RunQueue Tasks
> ERROR: bbexample-lt-1.0-r0 do_compile: oe_runmake failed
> ERROR: bbexample-lt-1.0-r0 do_compile: Function failed: do_compile (log file is located at /home/ken/Devtools/Yocto/poky/build/tmp/work/i586-poky-linux/bbexample-lt/1.0-r0/temp/log.do_compile.7416)
> ERROR: Logfile of failure stored in: /home/ken/Devtools/Yocto/poky/build/tmp/work/i586-poky-linux/bbexample-lt/1.0-r0/temp/log.do_compile.7416
> Log data follows:
> | DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common']
> | DEBUG: Executing shell function do_compile
> | NOTE: make
> | make  all-am
> | make[1]: Entering directory '/home/ken/Devtools/Yocto/poky/build/tmp/work/i586-poky-linux/bbexample-lt/1.0-r0/build'
> | make[1]: *** **_No rule to make target '.libs/libbbexample.la', needed by 'bbexample'_**.  Stop.
> | make[1]: Leaving directory '/home/ken/Devtools/Yocto/poky/build/tmp/work/i586-poky-linux/bbexample-lt/1.0-r0/build'
> | Makefile:360: recipe for target 'all' failed
> | make: *** [all] Error 2
> | ERROR: oe_runmake failed
> | WARNING: exit code 1 from a shell command.
> | ERROR: Function failed: do_compile (log file is located at /home/ken/Devtools/Yocto/poky/build/tmp/work/i586-poky-linux/bbexample-lt/1.0-r0/temp/log.do_compile.7416)
> ERROR: Task (/home/ken/Devtools/Yocto/poky/meta-example/recipes-example/bbexample/bbexample-lt_1.0.bb:do_compile) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 443 tasks of which 442 didn't need to be rerun and 1 failed.
> NOTE: Writing buildhistory
> 
> Summary: 1 task failed:
>   /home/ken/Devtools/Yocto/poky/meta-example/recipes-example/bbexample/bbexample-lt_1.0.bb:do_compile
> Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by ajlennon** [comment]
@FavoRiteKK can you take a look at the latest commits here and to meta-example.

 I was seeing the same build issues and with a couple of changes it's now building for me

**Comment by FavoRiteKK** [comment]
@ajlennon 
Thank you! It worked.

**Comment by ajlennon** [comment]
Great news. Thanks for reporting the problem @FavoRiteKK
